### ISSUE TITLE
Feature: 5 day weather forecast 

### ISSUE THREAD

**Issue by Morningstar88** [Morningstar88/kalki-search#10]
Weather APIs all have restriction so this will take a bit of research.

**Comment by Microflow** [comment]
### Works but only one city. Only 1 day. Would be OK for Taipei right now. Does it work for Taipei?

http://jsfiddle.net/23HQC/653/

**Comment by Microflow** [comment]
## Open Weather Map. Looks Good:

https://openweathermap.org/price

**Comment by Microflow** [comment]
Working but only one day. Look in the docs for later:

https://codepen.io/minggas/pen/WMmwMM

Displays weird name. Zhuzilin instead of Taipei.
