### ISSUE TITLE
Browser Needs to Geolocate and serve projects based on user location.

### ISSUE THREAD

**Issue by Morningstar88** [Morningstar88/kalki-search#20]
1) Links must say "Awesome Taipei" "Awesome Budapest" etc.

Done!

http://jsfiddle.net/cbtzzLjs/10/

2) Must serve specific local projects.

**Comment by Microflow** [comment]
YOU ARE HERE JSFIDDLE. Doesn't return name:

https://jsfiddle.net/user2314737/8ndjuoyj/

**Comment by Microflow** [comment]
CITY NAME, STACK-OVERFLOW:

https://stackoverflow.com/questions/6797569/get-city-name-using-geolocation

**Comment by Microflow** [comment]
MORE WITH CITY NAMES AND IP LOCATORS

https://stackoverflow.com/questions/409999/getting-the-location-from-an-ip-address/40022411#40022411

**Comment by Microflow** [comment]
##TUTORIALS

HTML5 Geolocation Tutorial:

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation
